name: Windows Natvie Electrum

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install deps
        run: pip install requests
      - name: Locale updates
        run: ./contrib/pull_locale
      - name: install dependencies
        run: apt-get install -qy wget gnupg2 dirmngr python3-software-properties software-properties-common libssl-dev
      - name: install dependencies
        run: apt-get install -qy git p7zip-full make mingw-w64 autotools-dev autoconf libtool gettext python3-scrypt
      - name: Run docker build
        run: ./contrib/build-wine/build.sh
        shell: bash

      - name: Set version env
        if: startsWith(github.ref, 'refs/tags/')
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})

      - name: Upload binaries to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./contrib/build-wine/dist/electrum-${{ env.RELEASE_VERSION }}-portable.exe
          asset_name: electrum-${{ env.RELEASE_VERSION }}-portable.exe
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload binaries to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./contrib/build-wine/dist/electrum-${{ env.RELEASE_VERSION }}-setup.exe
          asset_name: electrum-${{ env.RELEASE_VERSION }}-setup.exe
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload binaries to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./contrib/build-wine/dist/electrum-${{ env.RELEASE_VERSION }}.exe
          asset_name: electrum-${{ env.RELEASE_VERSION }}.exe
          tag: ${{ github.ref }}
          overwrite: true
